version: '3.2'

networks:
  taskholder:
    driver: bridge

services:

  nginx_taskholder:
    container_name: nginx_taskholder
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../:/application
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8905:80
    links:
      - 'phpfpm_taskholder'
    networks:
      - taskholder

  phpfpm_taskholder:
    container_name: phpfpm_taskholder
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ../:/application
      - ../docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      - taskholder

  pgsql_taskholder:
    container_name: pgsql_taskholder
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=taskholder_user
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=taskholder_db
    ports:
      - 54320:5432
    networks:
      - taskholder